<?php
/**
 * Event
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PocketSmith
 *
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Event Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Event implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Event';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'category' => '\OpenAPI\Client\Model\Category',
        'scenario' => '\OpenAPI\Client\Model\Scenario',
        'amount' => 'float',
        'amount_in_base_currency' => 'float',
        'currency_code' => 'string',
        'date' => 'string',
        'colour' => 'string',
        'note' => 'string',
        'repeat_type' => 'string',
        'repeat_interval' => 'int',
        'series_id' => 'int',
        'series_start_id' => 'string',
        'infinite_series' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'category' => null,
        'scenario' => null,
        'amount' => null,
        'amount_in_base_currency' => null,
        'currency_code' => null,
        'date' => null,
        'colour' => null,
        'note' => null,
        'repeat_type' => null,
        'repeat_interval' => null,
        'series_id' => null,
        'series_start_id' => null,
        'infinite_series' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'category' => false,
		'scenario' => false,
		'amount' => false,
		'amount_in_base_currency' => false,
		'currency_code' => false,
		'date' => false,
		'colour' => false,
		'note' => false,
		'repeat_type' => false,
		'repeat_interval' => false,
		'series_id' => false,
		'series_start_id' => false,
		'infinite_series' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'category' => 'category',
        'scenario' => 'scenario',
        'amount' => 'amount',
        'amount_in_base_currency' => 'amount_in_base_currency',
        'currency_code' => 'currency_code',
        'date' => 'date',
        'colour' => 'colour',
        'note' => 'note',
        'repeat_type' => 'repeat_type',
        'repeat_interval' => 'repeat_interval',
        'series_id' => 'series_id',
        'series_start_id' => 'series_start_id',
        'infinite_series' => 'infinite_series'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'category' => 'setCategory',
        'scenario' => 'setScenario',
        'amount' => 'setAmount',
        'amount_in_base_currency' => 'setAmountInBaseCurrency',
        'currency_code' => 'setCurrencyCode',
        'date' => 'setDate',
        'colour' => 'setColour',
        'note' => 'setNote',
        'repeat_type' => 'setRepeatType',
        'repeat_interval' => 'setRepeatInterval',
        'series_id' => 'setSeriesId',
        'series_start_id' => 'setSeriesStartId',
        'infinite_series' => 'setInfiniteSeries'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'category' => 'getCategory',
        'scenario' => 'getScenario',
        'amount' => 'getAmount',
        'amount_in_base_currency' => 'getAmountInBaseCurrency',
        'currency_code' => 'getCurrencyCode',
        'date' => 'getDate',
        'colour' => 'getColour',
        'note' => 'getNote',
        'repeat_type' => 'getRepeatType',
        'repeat_interval' => 'getRepeatInterval',
        'series_id' => 'getSeriesId',
        'series_start_id' => 'getSeriesStartId',
        'infinite_series' => 'getInfiniteSeries'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const REPEAT_TYPE_ONCE = 'once';
    public const REPEAT_TYPE_DAILY = 'daily';
    public const REPEAT_TYPE_WEEKLY = 'weekly';
    public const REPEAT_TYPE_FORTNIGHTLY = 'fortnightly';
    public const REPEAT_TYPE_MONTHLY = 'monthly';
    public const REPEAT_TYPE_YEARLY = 'yearly';
    public const REPEAT_TYPE_EACH_WEEKDAY = 'each weekday';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRepeatTypeAllowableValues()
    {
        return [
            self::REPEAT_TYPE_ONCE,
            self::REPEAT_TYPE_DAILY,
            self::REPEAT_TYPE_WEEKLY,
            self::REPEAT_TYPE_FORTNIGHTLY,
            self::REPEAT_TYPE_MONTHLY,
            self::REPEAT_TYPE_YEARLY,
            self::REPEAT_TYPE_EACH_WEEKDAY,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('category', $data ?? [], null);
        $this->setIfExists('scenario', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('amount_in_base_currency', $data ?? [], null);
        $this->setIfExists('currency_code', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('colour', $data ?? [], null);
        $this->setIfExists('note', $data ?? [], null);
        $this->setIfExists('repeat_type', $data ?? [], null);
        $this->setIfExists('repeat_interval', $data ?? [], null);
        $this->setIfExists('series_id', $data ?? [], null);
        $this->setIfExists('series_start_id', $data ?? [], null);
        $this->setIfExists('infinite_series', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getRepeatTypeAllowableValues();
        if (!is_null($this->container['repeat_type']) && !in_array($this->container['repeat_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'repeat_type', must be one of '%s'",
                $this->container['repeat_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id The unique identifier of the event.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets category
     *
     * @return \OpenAPI\Client\Model\Category|null
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param \OpenAPI\Client\Model\Category|null $category category
     *
     * @return self
     */
    public function setCategory($category)
    {
        if (is_null($category)) {
            throw new \InvalidArgumentException('non-nullable category cannot be null');
        }
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets scenario
     *
     * @return \OpenAPI\Client\Model\Scenario|null
     */
    public function getScenario()
    {
        return $this->container['scenario'];
    }

    /**
     * Sets scenario
     *
     * @param \OpenAPI\Client\Model\Scenario|null $scenario scenario
     *
     * @return self
     */
    public function setScenario($scenario)
    {
        if (is_null($scenario)) {
            throw new \InvalidArgumentException('non-nullable scenario cannot be null');
        }
        $this->container['scenario'] = $scenario;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float|null $amount The amount of the event.
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets amount_in_base_currency
     *
     * @return float|null
     */
    public function getAmountInBaseCurrency()
    {
        return $this->container['amount_in_base_currency'];
    }

    /**
     * Sets amount_in_base_currency
     *
     * @param float|null $amount_in_base_currency The amount of the event in the user's base currency.
     *
     * @return self
     */
    public function setAmountInBaseCurrency($amount_in_base_currency)
    {
        if (is_null($amount_in_base_currency)) {
            throw new \InvalidArgumentException('non-nullable amount_in_base_currency cannot be null');
        }
        $this->container['amount_in_base_currency'] = $amount_in_base_currency;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string|null
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string|null $currency_code The currency code of the event.
     *
     * @return self
     */
    public function setCurrencyCode($currency_code)
    {
        if (is_null($currency_code)) {
            throw new \InvalidArgumentException('non-nullable currency_code cannot be null');
        }
        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets date
     *
     * @return string|null
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param string|null $date The date of the event.
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets colour
     *
     * @return string|null
     */
    public function getColour()
    {
        return $this->container['colour'];
    }

    /**
     * Sets colour
     *
     * @param string|null $colour The CSS hex-style colour of the event.
     *
     * @return self
     */
    public function setColour($colour)
    {
        if (is_null($colour)) {
            throw new \InvalidArgumentException('non-nullable colour cannot be null');
        }
        $this->container['colour'] = $colour;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string|null
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string|null $note The note of the event.
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            throw new \InvalidArgumentException('non-nullable note cannot be null');
        }
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets repeat_type
     *
     * @return string|null
     */
    public function getRepeatType()
    {
        return $this->container['repeat_type'];
    }

    /**
     * Sets repeat_type
     *
     * @param string|null $repeat_type The repeat type of the event.
     *
     * @return self
     */
    public function setRepeatType($repeat_type)
    {
        if (is_null($repeat_type)) {
            throw new \InvalidArgumentException('non-nullable repeat_type cannot be null');
        }
        $allowedValues = $this->getRepeatTypeAllowableValues();
        if (!in_array($repeat_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'repeat_type', must be one of '%s'",
                    $repeat_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['repeat_type'] = $repeat_type;

        return $this;
    }

    /**
     * Gets repeat_interval
     *
     * @return int|null
     */
    public function getRepeatInterval()
    {
        return $this->container['repeat_interval'];
    }

    /**
     * Sets repeat_interval
     *
     * @param int|null $repeat_interval The repeat interval of how often the event takes place.
     *
     * @return self
     */
    public function setRepeatInterval($repeat_interval)
    {
        if (is_null($repeat_interval)) {
            throw new \InvalidArgumentException('non-nullable repeat_interval cannot be null');
        }
        $this->container['repeat_interval'] = $repeat_interval;

        return $this;
    }

    /**
     * Gets series_id
     *
     * @return int|null
     */
    public function getSeriesId()
    {
        return $this->container['series_id'];
    }

    /**
     * Sets series_id
     *
     * @param int|null $series_id The unique identifier of the series that the event belongs to.
     *
     * @return self
     */
    public function setSeriesId($series_id)
    {
        if (is_null($series_id)) {
            throw new \InvalidArgumentException('non-nullable series_id cannot be null');
        }
        $this->container['series_id'] = $series_id;

        return $this;
    }

    /**
     * Gets series_start_id
     *
     * @return string|null
     */
    public function getSeriesStartId()
    {
        return $this->container['series_start_id'];
    }

    /**
     * Sets series_start_id
     *
     * @param string|null $series_start_id The unique identifier of the series followed by the series's start date.
     *
     * @return self
     */
    public function setSeriesStartId($series_start_id)
    {
        if (is_null($series_start_id)) {
            throw new \InvalidArgumentException('non-nullable series_start_id cannot be null');
        }
        $this->container['series_start_id'] = $series_start_id;

        return $this;
    }

    /**
     * Gets infinite_series
     *
     * @return bool|null
     */
    public function getInfiniteSeries()
    {
        return $this->container['infinite_series'];
    }

    /**
     * Sets infinite_series
     *
     * @param bool|null $infinite_series Whether the event repeats and does not have an end date.
     *
     * @return self
     */
    public function setInfiniteSeries($infinite_series)
    {
        if (is_null($infinite_series)) {
            throw new \InvalidArgumentException('non-nullable infinite_series cannot be null');
        }
        $this->container['infinite_series'] = $infinite_series;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


