<?php
/**
 * AttachmentsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PocketSmith
 *
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AttachmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AttachmentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for attachmentsIdDelete
     *
     * Delete attachment.
     *
     */
    public function testAttachmentsIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for attachmentsIdGet
     *
     * Get attachment.
     *
     */
    public function testAttachmentsIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for attachmentsIdPut
     *
     * Update attachment.
     *
     */
    public function testAttachmentsIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsIdAttachmentsGet
     *
     * List attachments in transaction.
     *
     */
    public function testTransactionsIdAttachmentsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsIdAttachmentsPost
     *
     * Assigns attachment to transaction.
     *
     */
    public function testTransactionsIdAttachmentsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsTransactionIdAttachmentsAttachmentIdDelete
     *
     * Unassigns attachment in transaction.
     *
     */
    public function testTransactionsTransactionIdAttachmentsAttachmentIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersIdAttachmentsGet
     *
     * Lists attachments in user.
     *
     */
    public function testUsersIdAttachmentsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersIdAttachmentsPost
     *
     * Create attachment in user.
     *
     */
    public function testUsersIdAttachmentsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
